# https://doc.traefik.io/traefik/
# options: docker run traefik:v3.3 --help

# NB
#    - Docker swarm do not work with ${VARIABLE}
#    - envsubst do not replace with default value, example ${VARIABLE:-default}

services:
    gateway:
        image: traefik:3.3
        volumes:
            - ./docker/gateway/config/:/config/:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
            # Probably mode: host will require for HTTP_X_FORWARDED headers
            #- target: 80
            #  published: 80
            #  protocol: tcp
            #  mode: host
            #- target: 443
            #  published: 443
            #  protocol: tcp
            #  mode: host
        networks:
            - gateway-network
        environment:
            TZ: "UTC"

    api-proxy:
        image: ${REGISTRY}/${APP_ENV}-api-nginx:${IMAGE_TAG}
        networks:
            - gateway-network
            - default

    api-php-fpm:
        image: ${REGISTRY}/${APP_ENV}-php-fpm:${IMAGE_TAG}
        secrets:
            - db_password

    api-php-cli:
        image: ${REGISTRY}/${APP_ENV}-php-cli:${IMAGE_TAG}
        secrets:
            - db_password

secrets:
    db_password:
        file: ./docker/secrets/db_password

networks:
    gateway-network:
        name: gateway-network
        external: true
