# https://doc.traefik.io/traefik/
# options: docker run traefik:v3.3 --help

services:
    gateway:
        image: traefik:3.3
        volumes:
            - ./docker/gateway/config/:/config/:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
        networks:
            - proxy-public
        environment:
            TZ: "UTC"

    api:
        image: ${REGISTRY:-localhost}/${APP_ENV:-local}-api-nginx:${IMAGE_TAG:-latest}
        networks:
            - proxy-public
            - default

    api-php-fpm:
        image: php:8.4-fpm-bookworm
        secrets:
            - db_password

secrets:
    db_password:
        file: ./docker/secrets/db_password

networks:
    proxy-public:
        name: proxy-public
        external: true
